[package]
name = "move_files_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.23"
egui = "0.23"
rfd = "0.10"
walkdir = "2.3"

[dependencies.winapi]
version = "0.3.9"
features = ["winuser", "windef"]