[package]
name = "move_files_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"
egui = "0.30.0"
rfd = "0.15.2"
walkdir = "2.5.0"

[dependencies.winapi]
version = "0.3.9"
features = ["winuser", "windef"]